config/routes.rb
Rails.application.routes.draw do
  # gestione sessione omniauth e user normale
  get '/auth/:provider/callback', :to =>'sessions#create'
  get '/auth/failure', :to =>  redirect('/')# 'sessions_omniauth#failure'
  post 'rate' => 'rater#create'
  default_url_options :host => "localhost"
  root                     'mapbox#show'
  get 'dashboard'				=> 'mapbox#show'
  get 'signup'  => 'users#new'
  delete 'destroy' => 'users#destroy'
  get 'login'   => 'sessions#new'
  post'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get 'redirect', to: 'calendars#redirect'
  get 'callback', to: 'calendars#callback'
  put 'destroy_avatar' => 'rooms#destroy_avatar'
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :users do
    get 'achievements' => 'users#achievements'
    post 'destroy' => 'users#destroy'
    member do
      put "like" => "users#upvote"
    end
  end
  
  resources :avatars
  
  resources :rooms do
    post 'invite_user' =>'rooms#invite_user_to_room'
    post 'add_event' => 'calendars#add_event'
    resources :powers
    resources :messages do
      post 'pin'=>'messages#pin'
    end
    resources :reservations do
      resources :swap_reservations
    end
  end


  resources :conversations do
    resource :directs
  end


  #SE NON CI SONO ALTRE ROUTES, SIGNIFICA CHE L'ELEMENTO NON ESISTE ->
  match '/change'=>'application#change_availability', via: :all
  match '*path' => 'application#render_404', via: :all
end

app/models/message.rb
class Message < ApplicationRecord

	belongs_to :user
	belongs_to :room

	validates :user, presence: true
	validates :room, presence: true
	validates :body, presence: true


	def change_pin
		self.pinned=!self.pinned
		self.save
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!, only: [:create]
	before_action :set_room

	def index
		render :layout => false
		@messages = @room.messages
	end
	
	def create
		
		if current_user
			@message = @room.messages.build(message_params)
			@message.user = current_user
			
			if @message.save!
				respond_to do |format|
					format.html
				end
				
			else
				flash[:danger] = "Errore creazione"
			end
		end

		respond_to do |format|
			format.html
		end

	end

	def pin
		oldone = Message.find_by(pinned: true)
		oldone.change_pin if oldone
		newone = Message.find(params[:message_id])
		newone.change_pin
		respond_to do |format|
			format.html {redirect_to newone.room}
		end
	end

	def edit
		@to_edit=Message.find(params[:id])
		@room=Room.find_by(id: @to_edit.room_id)
		
	end

	def update
		@to_edit=Message.find(params[:id])
		@to_edit.body=params[:message][:body]
		@to_edit.save!
		respond_to do |format|
			format.html {redirect_to @to_edit.room}
		end

	end
	private
		def set_room
			@room = Room.friendly.find(params[:room_id])
		end

		def authenticate_user!
			redirect_to login_path if !current_user
		end

		def message_params
			params.require(:message).permit(:body,:id)
		end

end

app/views/messages/edit.html.haml
- provide(:title, "edit message") 
.container
  %h1 Edit message

  =form_for [@room,@to_edit] do |m|
    =m.text_field :body
    =m.submit "Update message", class: "btn btn-primary"
  

app/views/messages/index.html.haml
-@room.messages.each do |m| #Index.html.haml
    .test

        %p
            %strong 
                =link_to User.find(m.user_id).username, user_path(m.user) 
            =m.body
            
            -if current_user && (current_user.admin? || current_user.powers.exists?(room_id: @room.id))
                
                =link_to edit_room_message_path(@room.id, m.id) do
                    =hidden_field_tag :id, m.id
                    =image_tag('gear.svg',class:'edit')
        
                =link_to room_message_pin_path(@room.id,m.id),method: :post do
                    =image_tag('pin.svg',class:'pin')
                
            