config/routes.rb
Rails.application.routes.draw do
  # gestione sessione omniauth e user normale
  get '/auth/:provider/callback', :to =>'sessions#create'
  get '/auth/failure', :to =>  redirect('/')# 'sessions_omniauth#failure'
  post 'rate' => 'rater#create'
  default_url_options :host => "localhost"
  root                     'mapbox#show'
  get 'dashboard'				=> 'mapbox#show'
  get 'signup'  => 'users#new'
  delete 'destroy' => 'users#destroy'
  get 'login'   => 'sessions#new'
  post'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get 'redirect', to: 'calendars#redirect'
  get 'callback', to: 'calendars#callback'
  put 'destroy_avatar' => 'rooms#destroy_avatar'
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :users do
    get 'achievements' => 'users#achievements'
    post 'destroy' => 'users#destroy'
    member do
      put "like" => "users#upvote"
    end
  end
  
  resources :avatars
  
  resources :rooms do
    post 'invite_user' =>'rooms#invite_user_to_room'
    post 'add_event' => 'calendars#add_event'
    resources :powers
    resources :messages do
      post 'pin'=>'messages#pin'
    end
    resources :reservations do
      resources :swap_reservations
    end
  end


  resources :conversations do
    resource :directs
  end


  #SE NON CI SONO ALTRE ROUTES, SIGNIFICA CHE L'ELEMENTO NON ESISTE ->
  match '/change'=>'application#change_availability', via: :all
  match '*path' => 'application#render_404', via: :all
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token, :activation_token, :reset_token
    before_create :create_activation_digest
    has_many :achievements
    has_many :invitations, :class_name => self.to_s, :as => :invited_by
    acts_as_votable
    acts_as_voter
    before_save :downcase_email
    validates :username, presence: true, :length => { :maximum => 20 }, uniqueness: true;
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence:   true,
                      format:     { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
                      
    has_secure_password
    validates :password, length: { minimum: 8,maximum:15 }, confirmation: {case_sensitive:true},allow_blank: true; 
    validates :password_confirmation, presence: true,allow_blank: true;
  
    has_many :rooms, dependent: :destroy
    
    has_many :powers, dependent: :destroy
    has_many :reservations, dependent: :destroy

    has_many :active_requests, class_name: 'SwapReservation', :foreign_key => 'active_user'
    has_many :passive_requests, class_name: 'SwapReservation', :foreign_key => 'passive_user'
    
    has_many :messages

    acts_as_messageable
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest,  User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)    
    end
      
    
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    def award(achievement)
        achievements << achievement.new
    end

    def awarded?(achievement)
        achievements.count(:conditions => { :type => achievement }) > 0
    end

    def upvote
        @user.upvote_from current_user
        redirect_to users_path
    end

    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    def activate
        update_attribute(:activated,    true)
        update_attribute(:activated_at, Time.zone.now)
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

    private 

        def downcase_email
            self.email = email.downcase
        end

        def create_activation_digest
            self.activation_token  = User.new_token
            self.activation_digest = User.digest(activation_token)
        end
end

class Achievement < ActiveRecord::Base
    belongs_to :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @hashed=Digest::MD5.hexdigest(@user.id.to_s)
  end

  def achievements
    @user=User.find(params[:user_id])
    @scala=100
    if(@user.cached_votes_up>@scala)
      @scala=@scala*2
    end
    render 'achievements'
  end
  
  def invitation
    existing_user=User.find_by(email: email)
    self.user = if existing_user.present?
                  existing_user
                else
                  User.invite!(email: email)
                end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    
    if @user.save
      @user.activated=true
      @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    auth_hash = request.env['omniauth.auth']
    if auth_hash
      User.find_by(email: auth_hash['info']['email'].downcase).destroy
    else
    User.find(params[:email]).destroy
    flash[:success] = "User deleted"
    redirect_to(root_url)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:username,:email,:password,:password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/achievements.html.haml
.container-fluid{:style => 'padding-left: 15%,padding-right:15%'}
    .row
        .col-lg-12
        %br
            %h1 Hey #{@user.username}, here are your achievements:
        %br
    .row
        .col-lg-6
            %br
            %br
            %label 
                %h3 Your average score:
                %h3 #{@user.cached_votes_up}
        .col-lg-6
            %br
            %br
            %label
                %h3 Your XP:
                .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "70", :role => "progressbar", :style => "width:70%"} #{@user.cached_votes_up}/#{@scala}
                     

app/views/users/edit.html.haml
!!!5
%html{:lang => "it"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SignUp Inline
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    .container-fluid{:style => "padding-left:10%;padding-right:10%;"}
      - provide(:title, "Edit user")
      .row
        .col-lg-12
          = form_for(@user) do |f|
            %br
            = render 'shared/error_messages'
            = f.label :username
            = f.text_field :username, class: 'form-control'
            %br
            = f.label :email
            = f.email_field :email, class: 'form-control'
            %br
            = f.label :password
            = f.password_field :password, class: 'form-control'
            %br
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'form-control'
            %br
            = f.submit "Save changes", class: "btn btn-success", :data => {:confirm => "Are you sure of the changes?"}
            =link_to @user ,:data => {:confirm => "Are you sure to discard the changes?"} do  
              %input.btn.btn-danger{:type =>"submit", :value => "Discard"}/

app/views/users/index.html.haml
!!!5
%html{:lang => "it"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Home Inline
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    .container-fluid
      .row
        .col-lg-12
          %center
            %h1 WELCOME TO INLINE APP
            %br
            =link_to login_path(@session) do   
              %input.btn.btn-success{:type => 'submit', :value => 'login'}/
            =link_to signup_path(@user) do   
              %input.btn.btn-primary{:type => 'submit', :value => 'signup'}/
            
            

app/views/users/new.html.haml
!!!5
%html{:lang => "it"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SignUp Inline
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    .container-fluid{:style => "padding-left:10%;padding-right:10%;"}
      .row
        .col-lg-12{:style => "margin-top:5%"}
          %center
            %h3 Signup
            %br/
            = form_for(@user) do |f|
              = render 'shared/error_messages'
              .form-group
                %h3 Username
                %input.form-control{:maxlength => "20",:id => "user_username", :name => "user[username]", :required => "", :type => "username"}/
              .form-group
                %h3 Email
                %input.form-control{:maxlength => "50",:id => "user_email", :name => "user[email]", :placeholder => "prova@example.com", :required => "", :type => "email"}/
              .form-group
                %h3 Password
                %input.form-control{:maxlength => "30",:id => "user_password", :name => "user[password]", :required => "", :type => "password"}/
              .form-group
                %h3 Password Confirmation
                %input.form-control{:maxlength => "30",:id => "user_passwordconfirmation", :name => "user[password_confirmation]", :required => "", :type => "password"}/
              %input.btn.btn-sm.btn-success{:type => "submit", :value => "Signup"}/
              %input.btn.btn-sm.btn-danger{:type => "reset", :value => "Reset"}/

app/views/users/show.html.haml
.container-fluid{:style => 'padding-left: 15%,padding-right:15%'}
  .row
    .col-lg-6
      %label
        %h1 USERNAME:
        %p #{@user.username}
      %br
      %label
        %h1 EMAIL:
        %p #{@user.email}
      %br
      =link_to user_achievements_path(@user) do
        %input.btn.btn-sm.btn-success{:type => "submit", :value => "Achievements"}
    .col-lg-6
      %label
        %h1 YOUR ID: 
        %p  #{@hashed}
      %br
      %label
        %h1 REFERRAL LINK:
        %a{:href => "http://inlineapp.com/login"} http://inlineapp.com/#{@hashed}
      %br
      %br
      =link_to edit_user_path(@user)  do 
        %input.btn.btn-sm.btn-warning{:type => "submit", :value => "Edit Profile"}/
      =link_to @user, method: :delete, title: 'Delete User', :data => {:confirm => 'Are you sure you want to delete your profile?'} do
        %input.btn.btn-sm.btn-danger{:type =>"submit", :value => "Delete profile"}/
  .row
    .col-lg-6
      %strong Rooms Attended: 
      %p#rooms-attended
        =@user.rooms_attended
    .col-lg-6
      %br    
      %label 
        %h3 INVITE USER:
        = form_for(@user) do |f|
          .form-group
            %input.form-control{:maxlength => "50",:id => "user_email", :name => "user[email]", :placeholder => "email", :required => "true", :type => "email"}/
            %input.btn.btn-sm.btn-success{:type => "submit", :value => "Invite"}/