config/routes.rb
Rails.application.routes.draw do
  # gestione sessione omniauth e user normale
  get '/auth/:provider/callback', :to =>'sessions#create'
  get '/auth/failure', :to =>  redirect('/')# 'sessions_omniauth#failure'
  post 'rate' => 'rater#create'
  default_url_options :host => "localhost"
  root                     'mapbox#show'
  get 'dashboard'				=> 'mapbox#show'
  get 'signup'  => 'users#new'
  delete 'destroy' => 'users#destroy'
  get 'login'   => 'sessions#new'
  post'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get 'redirect', to: 'calendars#redirect'
  get 'callback', to: 'calendars#callback'
  put 'destroy_avatar' => 'rooms#destroy_avatar'
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :users do
    get 'achievements' => 'users#achievements'
    post 'destroy' => 'users#destroy'
    member do
      put "like" => "users#upvote"
    end
  end
  
  resources :avatars
  
  resources :rooms do
    post 'invite_user' =>'rooms#invite_user_to_room'
    post 'add_event' => 'calendars#add_event'
    resources :powers
    resources :messages do
      post 'pin'=>'messages#pin'
    end
    resources :reservations do
      resources :swap_reservations
    end
  end


  resources :conversations do
    resource :directs
  end


  #SE NON CI SONO ALTRE ROUTES, SIGNIFICA CHE L'ELEMENTO NON ESISTE ->
  match '/change'=>'application#change_availability', via: :all
  match '*path' => 'application#render_404', via: :all
end

app/models/room.rb
class Room < ApplicationRecord
  include Friendlyable
  
  before_save {adjust_time unless event_id }
  
  after_save{
    Power.create(room_id: id, user_id: self.user_id) if self.powers.empty?
    update_event unless event_id
    change_unjoin_time unless max_unjoin_time
    schedule
  }
  
  before_destroy  {event_destroy}
  
  VALID_ROOM_NAME = /\A[a-z0-9\s]+\Z/i
  validates :user_id, presence: true
  
  validates :time_to, presence: true
  validates :time_from, presence: true
  
  validates :max_participants, presence: true, 
            numericality: {only_integer: true, greater_than_or_equal_to: 1}
  
  validates :name, presence: true, length: { in: 5..30 },
            format: {with: VALID_ROOM_NAME}
  validates :description, length: { maximum: 140 }
  
  belongs_to :user
  has_many :powers, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :messages
  
  has_attached_file :avatar, default_url: '//placehold.it/200'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/,
                                    size: {in: 0..1024.kilobytes}
  attr_accessor :delete_avatar

  def adjust_time
    self.time_to = Time.use_zone('Europe/Rome'){ Time.zone.local_to_utc(self.time_to) }.localtime
    self.time_from = Time.use_zone('Europe/Rome'){ Time.zone.local_to_utc(self.time_from) }.localtime
  end
  
  def change_unjoin_time
    self.update(max_unjoin_time: Time.at((Time.parse(self.time_from.to_s) - 1.hour).to_i))
  end

  
  #CREA UN EVENTO ALLA CREAZIONE DELLA ROOM
  def update_event
    event = Google::Apis::CalendarV3::Event.new({
      #NOME DESCRIZIONE E LOCATION DELL'EVENTO
      summary: self.name,
      description: self.description,
      location: self.address,
      
      #DATI DEL CREATORE, INIZIO EVENTO, FINE EVENTO
      organizer: {email: self.user.email, display_name: self.user.username},
      start:  Google::Apis::CalendarV3::EventDateTime.new(date_time: self.time_from.to_datetime.rfc3339),
      end:    Google::Apis::CalendarV3::EventDateTime.new(date_time: self.time_to.to_datetime.rfc3339),
      
      #RICCORRENZA VISIBILITÀ E PARTECIPANTI EVENTO
      #recurrence: self.recurrence,
      visibility: self.private ? 'private':'public',
    })
    cal = Inline::Application.config.cal
    #cal.authorization.update!(session[:authorization])
    if self.event_id.nil?

      event = cal.insert_event('primary', event)
      self.update(event_id: event.id)
      
    else
    
      event = cal.update_event('primary', self.event_id, event)
      self.update(event_id: event.id)
    end
  end
  
    #DISTRUGGE EVENTO SUL CALENDAR
  def event_destroy
    cal = Inline::Application.config.cal
    event = cal.get_event('primary', event_id)
    cal.delete_event('primary', event_id) unless event.nil?
  end

  def rule
    IceCube::Rule.from_hash recurrence
  end

  serialize :recurrence, Hash
  def recurrence=(value)
    if value != 'null' && RecurringSelect.is_valid_rule?(value)
      super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
    else
      super(nil)
    end
  end

  def schedule
    if recurrence.empty?
      [self]
    else
      schedule = IceCube::Schedule.new(time_from)
      schedule.add_recurrence_rule(rule)
      start_date  = time_from.beginning_of_month.beginning_of_week 
      end_date    = time_from + 60*60*24*30 #UN MESE DOPO (60 s * 60 m * 24 h * 30g)
      difference  = time_to - time_from
      schedule.occurrences(end_date).map do |date|
        #LE SETTIAMO PRIVATE PER NON INTASARE.
        logger.debug "DATAA #{date}"
        new_room = user.rooms.create!(name: name, time_from: date, 
                            time_to: date + difference, 
                            description: description,
                            address: address,
                            longitude: longitude,
                            latitude: latitude,
                            fifo: fifo, private: true,
                            max_participants: max_participants
                          )
      end
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:edit, :update, :destroy, :destroy_avatar]
  before_action :logged_in_user, only: [:new]
  before_action :correct_user, only: [:edit, :destroy]
  
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all 
  end
  
  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.friendly.find(params[:id])
    @reservations = @room.reservations
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      respond_to do |format|
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        flash[:success] = 'Room updated!'
        format.html { redirect_to edit_room_path(@room), success: 'Room was successfully updated.' }
        format.json { render :edit, status: :ok, location: @room }
      else
        flash[:danger] = 'Parametri non validi!'
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_avatar
    @room.avatar.destroy
    @room.save!
    redirect_to edit_room_path(@room)
  end

  def invite_user_to_room
    room=Room.find_by(id: params[:room_id])
    sender=current_user
    sendee=User.find_by(username: params[:username])
    if sendee
      
      sender.send_message(sendee,
    "Hey #{sendee.username}, #{sender.username} has invited you to check out #{root_url}rooms/#{room.hash_id}","You have been invited to #{room.name}")
      respond_to do |format|
        format.html{redirect_to room,notice: 'User has been invited!'}
      end
    else
      respond_to do |format|
        format.html{redirect_to room,notice: 'ERROR: User does not exist'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :recurrence, :address, :max_participants, :latitude, :longitude, :time_from, :time_to, :avatar, :datetime, :user_id, :fifo, :private, :delete_avatar, :recurrence)
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
     def correct_user
      redirect_to(root_url) unless (!current_user.nil? && current_user.powers.exists?(room_id: @room.id))
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper

  #METODO USATO PER RENDERIZZARE MAPPA SU ROOM#SHOW
  #SE L'INDIRIZZO/LATITUDINE/LONGITUDE È NULL, NON HO LOCATION
  def has_no_location
    @room = Room.friendly.find(params[:id])
    ( !@room.latitude || !@room.longitude || !@room.address )
  end
  
  #METODO USATO PER SAPERE SE POSSO EDITARE LA ROOM
  #SE SONO ADMIN O HO POTERI SI
  def do_i_matter?
    @room = Room.friendly.find(params[:id])
    current_user && (current_user.admin? || current_user.powers.exists?(room_id: @room.id))
  end
  
  #METODO USATO PER SAPERE SE POSSO PRENOTARMI
  #SE NON SONO LOGGATO, NON HO POTERI E NON HO UNA PRENOTAZIONE ESISTENZE POSSO
  def can_i_reserve?
    @room = Room.friendly.find(params[:id])
    !current_user || (!do_i_have_powers? && !current_user.reservations.exists?(room_id: @room.id))
  end
  
  #METODO USATO PER CAPIRE SE POSSO AGGIUNGERE O TOGLIERE ROOM HOST
  #SE SONO ADMIN O OWNER RITORNA TRUE
  def do_i_have_superpower?
    @room = Room.friendly.find(params[:id])
    current_user && ( current_user.admin? || @room.user.id = current_user.id )
  end
  
  #METODO USATO PER CAPIRE SE SONO ROOM HOST/OWNER
  #SE HO I POTERI TORNA TRUE (SEMI DOPPIONE DI DO_I_MATTER, USATO SOLO PER DECIDERE QUALE BOTTONE RENDERIZZARE)
  def do_i_have_powers?
    @room = Room.friendly.find(params[:id])
    current_user && current_user.powers.exists?(room_id: @room.id)
  end
  
end

app/views/rooms/_form_edit.html.haml
.row
  .col-lg-9
    %h1 Modifica la room
  .col-lg-3.text-right
    =link_to 'Go back to the room', @room
%hr/

#unjointime_hidden
  =@room.max_unjoin_time

#timefrom_hidden
  =@room.time_from
  
.row
  / left column
  .col-md-3
    .row
      .container.text-center
        =link_to 'Ripristina immagine predefinita', {action: :destroy_avatar, id:@room.id}, :method => :put
      %img.mx-auto.img-thumbnail{:alt => "avatar", :src => "#{@room.avatar.url}", :style => 'width: 200px; height: 200px'}
      = form_for @room, html: { multipart: true } do |f|
        .form-group
          = f.file_field :avatar, :title => "Search for a file to add", id: 'file_input', :style => "width:  100%;"
        %small
          L'immagine caricata verrà usata solo come thumbnail, dimensione consigliata 200x200
        .form-group
          = f.submit 'Upload', class: 'btn btn-outline-primary'
        
    .row.mt-2
      =form_for([@room, Power.new]) do |f|
        .input-group.mb-3
          =f.text_field :user_id, class: 'form-control', placeholder: 'Room host username'
          .input-group-append
            =f.submit 'Add', class: 'btn btn-outline-primary'
    .row{style: 'margin-top: -5%'}
      =link_to "Cancella la room", {action: :destroy}, :method => :delete
      %ul.list-group.list-group-flush.col-12
        -@room.powers.each do |p|
          %li.list-group-item
            .row
              .col-9.text-right.my-auto
                =link_to p.user.username, user_path(p.user)
              .col-3.text-left.my-auto
                -if p.user != current_user && p.user != @room.user
                  =form_for([@room, p.user.powers.find_by(room_id: @room.id)], html: {method: :delete}) do |f|
                    =f.submit 'x', class: 'btn btn-sm btn-danger', id: 'add_button'
                -else
                  %input.btn.btn-sm.btn-danger{type: 'submit', disabled: '', value: 'x', title: 'Non puoi rimuovere questo utente'}

      
  / edit form column
  .col-md-9.personal-info
    %h3 Personal info
    = form_for @room do |f|
      - if @room.errors.any?
        .mx-auto.form-group
          %h4.text-center
            = "#{pluralize(@room.errors.count, "error")} on the form:"
          %ul.mx-auto{:style => 'padding-left: 0px;'}
            - @room.errors.full_messages.each do |message|
              .text-center.alert.alert-danger= message  
      
      .form-group.row
        %label.col-lg-3 Nome Stanza:
        .col-lg-9
          = f.text_field :name, class: 'form-control', :disabled => ''
      .form-group.row
        %label.col-lg-3.control-label Descrizione:
        .col-lg-9
          = f.text_area :description, class: 'form-control', style: 'resize:none;'
      .form-group.row
        = f.text_field :address   , class: 'form-control', id: 'addr_input'
        = f.text_field :latitude  , class: 'form-control', id: 'lats_input'
        = f.text_field :longitude , class: 'form-control', id: 'lons_input'
      .form-group.row
        %label.col-lg-3.control-label Location: 
        
        #geocoder.col-lg-9
      .form-group.row
        %label.col-lg-3.control-label Max unjoin time:
        .col-lg-9
          = f.text_field :max_unjoin_time, class:'form-control', id: 'unjointime'
      .form-group.row
        #map
      .form-group.row
        %label.col-lg-3.control-label Visibilità stanza:
        .col-lg-9.row
          .col-lg-6.text-center
            = f.radio_button :private, false, :checked => !@room.private
            %label.control-label Publica
          .col-lg-6.text-center
            = f.radio_button :private, true, :checked => @room.private
            %label.control-label Privata
      
      .form-group.text-center
        =f.submit 'Save changes', class: 'btn btn-primary'
        %span
        =button_tag 'Cancel', type: 'reset', class: 'btn btn-default'
          
%hr/

:javascript
  
  $(document).ready(function(){
    $('#addr_input').hide();
    $('#lons_input').hide();
    $('#lats_input').hide();  
    $('#timefrom_hidden').hide();  
    $('#unjointime_hidden').hide();  
    render_map_for_room();
    $('#map').hide();
    
    var time_from = $('#timefrom_hidden').html();
    var max_unjoin_time = $('#unjointime_hidden').html();
    var dateFrom = $("#unjointime").flatpickr({ 
      enableTime: true,
      minDate: 'today',
      currentDate: max_unjoin_time,
      maxDate: time_from,
      altInput: true,
      altFromat: "F j, Y",
      dateFormat: 'Y-m-d H:i',
    });  
  });

app/views/rooms/_form_new.html.haml
%h1 Crea la stanza
%hr/
.row
  .col-md-12.personal-info
    = form_for @room do |f|
      - if @room.errors.any?
        .mx-auto.form-group
          %h4.text-center
            = "#{pluralize(@room.errors.count, "error")} on the form:"
          %ul.mx-auto{:style => 'padding-left: 0px;'}
            - @room.errors.full_messages.each do |message|
              .text-center.alert.alert-danger= message  
      
      .form-group.row
        %label.col-lg-3 Nome Stanza:
        .col-lg-9
          = f.text_field :name, class: 'form-control'
      .form-group.row
        %label.col-lg-3.control-label Tipo di coda:
        .col-lg-9
          .row
            .col-lg-6
              = f.radio_button :fifo, true, :checked => 'true'
              %label.control-label First in first out
            .col-lg-6
              = f.radio_button :fifo, false
              %label.control-label Choose your position
      .form-group.row
        %label.col-lg-3 Max partecipanti
        .col-lg-9
          = f.text_field :max_participants, class: 'form-control'
      .form-group.row
        %label.col-lg-3.control-label Descrizione:
        .col-lg-9
          = f.text_area :description, class: 'form-control', style: 'resize:none;'
      .form-group.row
        = f.text_field :address   , class: 'form-control', id: 'addr_input'
        = f.text_field :latitude  , class: 'form-control', id: 'lats_input'
        = f.text_field :longitude , class: 'form-control', id: 'lons_input'
      .form-group.row
        %label.col-lg-3.control-label Location: 
        #geocoder.col-lg-9
      .form-group.row#mapdiv
        #map
      .form-group.row
        %label.col-lg-3.control-label Visibilità stanza:
        .col-lg-9
          .row
            .col-lg-6
              = f.radio_button :private, false
              %label.control-label Publica
            .col-lg-6
              = f.radio_button :private, true
              %label.control-label Privata
      .form-group.row
        %label.col-lg-3.control-label Definizione temporale:
        .col-lg-9
          .row
            .col-lg-6#time_from_div
              = f.text_field :time_from, class: 'form-control', id: 'inputdateFrom', :placeholder => 'Data inizio...'
            .col-lg-6#time_to_div
              = f.text_field :time_to, class: 'form-control', id: 'inputdateTo', :placeholder => 'Data fine...'
      .form-group.row
        %label.col-lg-3.control-label Ricorrenza evento:
        .col-lg-9
          = f.select_recurring :recurrence, nil, :allow_blank => 'true'
      .form-group.row
        .col-lg-3
        .col-lg-9
          =f.submit 'Submit', class: 'btn btn-primary'
          %span
          =button_tag 'Cancel', type: 'reset', class: 'btn btn-default'
          
%hr/
 
:javascript
  $(document).ready(function(){
    render_map_for_room();
    $('#room_recurrence').addClass("form-control")
    $('#map_div').hide();
    
    $('#map_control').on('click', function(){
      $('#map_div').toggle();
    });
    
    $('#addr_input').hide();
    $('#lons_input').hide();
    $('#lats_input').hide();
    
    $('#reset_location').on('click', function(){
      $('#addr_input').val('');
      $('#lons_input').val('');
      $('#lats_input').val('');
    });
    
    
    var dateFrom = $("#inputdateFrom").flatpickr({ 
      enableTime: true,
      minDate: 'today',
      altInput: true,
      altFromat: "F j, Y",
      dateFormat: 'Y-m-d H:i',
      onChange(selectedDates, dateStr, instance){
        changeDateMinTo(selectedDates)
      }
    });
    
    var dateTo = $("#inputdateTo").flatpickr({
      enableTime: true,
      altInput: true,
      altFromat: "F j, Y",
      dateFormat: 'Y-m-d H:i',
      onChange(selectedDates, dateStr, instance){
        changeDateMaxFrom(selectedDates)
      }
    });

    
    function changeDateMinTo(date){
      dateTo.set('minDate', date[0])
    };
    
    function changeDateMaxFrom(date){
      dateFrom.set('maxDate', date[0])
    };
    
  });

app/views/rooms/_join.html.haml
-if @room.fifo
  - if current_user.nil?
    .form-group
      = link_to "Join", login_path, class: "btn btn-primary btn-block"
  - else
    = form_for([@room, Reservation.new], remote: true) do |f|
      = hidden_field_tag :user_id, current_user.id
      .form-group
        = f.submit "Join", class: "btn btn-primary btn-block", id: 'joinbutton'
-else
  = form_for([@room, Reservation.new], remote: true) do |f|
    = hidden_field_tag :user_id, current_user.id
    = hidden_field_tag :position, current_user.id
    .form-group
      = f.submit "Join", class: "btn btn-primary btn-block", id: 'joinbutton',  onclick: 'refreshingPartial()'

app/views/rooms/_remind.html.haml
-if current_user.reservations.exists?(room_id: @room.id)
  -@reservation = current_user.reservations.find_by(room_id: @room.id)
  =form_for([@room, @reservation], html: { method: :patch}, remote: true) do |f|
    
    =hidden_field_tag :room_id, @room.id
    =hidden_field_tag :user_id, current_user.id
    =hidden_field_tag :reminder, !@reservation.reminder
    -if !@reservation.reminder
      = f.submit "Email", class: "btn btn-success btn-block btn-sm", onclick: 'refreshingPartial()'
    -else
      = f.submit "Email", class: "btn btn-danger btn-block btn-sm", onclick: 'refreshingPartial()'

app/views/rooms/_unjoin.html.haml
= form_for([@room, current_user.reservations.find_by(room_id: @room.id)], html: { method: :delete}, remote: true) do |f|
  .form-group
    = f.submit "Unjoin", class: "btn btn-danger btn-block", id: 'unjoinbutton', onclick: 'refreshingPartial()'

app/views/rooms/edit.html.haml
- provide(:title, "edit #{@room.name}") 
.container
  = render 'form_edit'

app/views/rooms/index.html.haml
=month_calendar start_date_param: :time_from do |day|
  %div
    %strong= day.to_s(:long)
  

app/views/rooms/new.html.haml
- provide(:title, "Creazione room")
.container
  =render 'form_new'


  

app/views/rooms/show.html.haml
-provide(:title, @room.name)
.container-fluid{:style => 'padding-left: 15%; padding-right: 15%;'}
	%center
		%h2
			=@room.name
		%h5
			=@room.description
		-if do_i_matter?
			=link_to 'Edit room', edit_room_path

			=form_tag room_invite_user_path(@room.id) do 
				=text_field_tag :username
				=submit_tag 'Invita'

	.row.body-room
		.col-xl-3.col-lg-3.col-md-3.col-sm-12.col-12.border-right.text-center#infodiv
			%h4.text-center.my-auto.border-bottom
				Info
			%h5.text-center.my-2
				Partecipanti massimi:
				=@room.max_participants
			%img#roomavatar{src: "#{@room.avatar.url}"}
			-if !has_no_location				
				.row#map.mx-auto
				=@room.address
				%br
			
			%br
			.row
				.col-xl-2.col-lg-2.col-md-2.col-sm-2.col-2.my-auto
					%label.my-auto
						Start:
				.col-xl-10.col-lg-10.col-md-10.col-sm-10.col-10
					%input.text-center#dateEvent_from{:type => 'text'}
			%br
			.row
				.col-xl-2.col-lg-2.col-md-2.col-sm-2.col-2.my-auto
					%label.my-auto
						End:
				.col-xl-10.col-lg-10.col-md-10.col-sm-10.col-10
					%input.text-center#dateEvent_to{:type => 'text'}
		
			%h4.text-center.my-3

				Room host:
				
				%table.table
					%tbody
					-@room.powers.each do |p|
						%tr
							%td.text-center
								=link_to p.user.username, user_path(p.user)  
			
			=link_to 'Aggiungi evento al tuo calendar', {controller: 'calendars', action: 'add_event', room_id: @room.hash_id}, :method => 'post'
			=image_tag('google-icon.png', class: 'google-icon')
		.col-xl-6.col-lg-6.col-md-6.col-sm-12.col-12
			%ul.list-group.userlist#userlist.fixed-size-room		
			-if @room.fifo
				#joindiv
					-if can_i_reserve?
						-if can_delete?
							=render 'join'
						-else
							%button.btn.btn-danger.btn-lg{:disabled => ''}
								Tempo scaduto!
					-else
						-if do_i_have_powers?
							
						-else
							=render 'unjoin' 
				#reminderdiv{:style => 'margin-top: 10px'}
					-if !current_user.nil? && current_user.reservations.exists?(room_id: @room.id)
						=render 'remind' 
		.col-3.border-left
			#pinned.border-bottom
				-@room.messages.each do |m|
					-if m.pinned
						%h5 PINNED MESSAGE
						%p
							%strong
								=link_to User.find(m.user_id).	username
							=m.body
			#messages{:style =>'overflow-y:scroll;height:70vh'}
			-if current_user
				= form_for([@room, Message.new], remote: true) do |f|
					= hidden_field_tag :user_id, current_user.id
					.input-group.mb-3
						=f.text_field :body, class: "form-control",placeholder: "Insert your message...", autocomplete: "off",id:"chat_input"
						.input-group-append
							= f.button "Invia", class: "btn btn-primary btn-block",id:"chat_btn"
			-else
				.input-group.mb-3
					%input#chat_input{:type => 'text', :placeholder => 'Insert your message...', :autocomplete => 'off'}
					.input-group-append
						%button.btn.btn-primary.btn-block{:disabled => ''}
							Disabled
					%small
						Log in and join the queue first!
	
	
:javascript
	var url = getRightUrl();
	var scroll= true;
	
	

	$("#messages").mouseenter(function(){scroll=false});
	$("#messages").delay(10000).mouseleave(function(){scroll=true;})
	
	$("#new_message").submit(function(e){
		e.preventDefault(); 
		this.submit();
		$("#chat_input").val("");
		$('#messages').load(url+'/messages');
		scrollDown(1);
	})

	$(document).ready(function(){	
		refreshingPartial();
		getParticipants();
		scrollDown(10);
		var room_json = init(url+'.json');
		$("#dateEvent_from").flatpickr({ 
			enableTime: true,
			altInput: true,
			altFromat: "F j, Y",
			dateFormat: 'Y-m-d H:i',
			minDate: room_json.time_from,
			maxDate: room_json.time_from,
			defaultDate: room_json.time_from,
		});
		$("#dateEvent_to").flatpickr({ 
			enableTime: true,
			altInput: true,
			altFromat: "F j, Y",
			dateFormat: 'Y-m-d H:i',
			minDate: room_json.time_to,
			maxDate: room_json.time_to,
			defaultDate: room_json.time_to
		})

		if($('#map').length) {      
			render_map_for_room_show(url+'.json');
			$('.marker').hide();
		}

		//SETTIAMO L'ALTEZZA AL VALORE DI INFO
		var height = $("#infodiv").height();
		
		$(".fixed-size-room").height(height);
	});
	
	function getParticipants(){
		setTimeout(function(){
			refreshingPartial();
			getParticipants();
		}, 5000);

	}	
	function refreshingPartial(){
		setTimeout(function(){
			$('#userlist').load(url+'/reservations');
			$('#messages').load(url+'/messages');
			if (scroll){
				scrollDown(500);}
			
		}, 1000);
	}

	function scrollDown(speed){
		$('#messages').stop().animate({scrollTop: $('#messages')[0].scrollHeight},speed)
	}

	function sleep_ms(millisecs) {
	var initiation = new Date().getTime();
	while ((new Date().getTime() - initiation) <millisecs);
	}