config/routes.rb
Rails.application.routes.draw do
  # gestione sessione omniauth e user normale
  get '/auth/:provider/callback', :to =>'sessions#create'
  get '/auth/failure', :to =>  redirect('/')# 'sessions_omniauth#failure'
  post 'rate' => 'rater#create'
  default_url_options :host => "localhost"
  root                     'mapbox#show'
  get 'dashboard'				=> 'mapbox#show'
  get 'signup'  => 'users#new'
  delete 'destroy' => 'users#destroy'
  get 'login'   => 'sessions#new'
  post'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get 'redirect', to: 'calendars#redirect'
  get 'callback', to: 'calendars#callback'
  put 'destroy_avatar' => 'rooms#destroy_avatar'
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :users do
    get 'achievements' => 'users#achievements'
    post 'destroy' => 'users#destroy'
    member do
      put "like" => "users#upvote"
    end
  end
  
  resources :avatars
  
  resources :rooms do
    post 'invite_user' =>'rooms#invite_user_to_room'
    post 'add_event' => 'calendars#add_event'
    resources :powers
    resources :messages do
      post 'pin'=>'messages#pin'
    end
    resources :reservations do
      resources :swap_reservations
    end
  end


  resources :conversations do
    resource :directs
  end


  #SE NON CI SONO ALTRE ROUTES, SIGNIFICA CHE L'ELEMENTO NON ESISTE ->
  match '/change'=>'application#change_availability', via: :all
  match '*path' => 'application#render_404', via: :all
end

app/views/layouts/_dashboard.html.haml
.dashboard{:style=>"background-color:#f2f2f2;height:200px;"}  
  %h1 Admin's Dashboard
  .tools{:style=>"padding-left:10px;padding-top:10px;"}
    -if $should_be_offline==true
      =link_to "/change" do
        %button.btn.btn-success#restore Restore website
      
       
    -else
      
      =link_to "/change" do
        %button.btn.btn-danger#suspend Suspend website
      
      = form_tag destroy_path do
        %br 
        =text_field_tag :email
        =submit_tag "Delete user", class: "btn btn-danger", :data => {:confirm => "Are you sure you want to delete this user?"}
        
        

app/views/layouts/_footer.html.haml
%section#footer
  .container
    .row
      .col-xs-12.col-sm-12.col-md-12.mt-2.mt-sm-5.mb-2.mb-sm-5
        %ul.list-unstyled.list-inline.social.text-center
          %li.list-inline-item
            %a{:href => "javascript:void();"}
              %i.fa.fa-facebook
          %li.list-inline-item
            %a{:href => "javascript:void();"}
              %i.fa.fa-twitter
          %li.list-inline-item
            %a{:href => "javascript:void();"}
              %i.fa.fa-instagram
          %li.list-inline-item
            %a{:href => "javascript:void();"}
              %i.fa.fa-google-plus
          %li.list-inline-item
            %a{:href => "javascript:void();", :target => "_blank"}
              %i.fa.fa-envelope

    .row.text-center.text-xs-center.text-sm-left.text-md-left
      .col-xs-12.col-sm-4.col-md-4
        %h5 Quick links
        %ul.list-unstyled.quick-links
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              Home
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              About
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              FAQ
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              Get Started
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              Videos
      .col-xs-12.col-sm-4.col-md-4
        %h5 Quick links
        %ul.list-unstyled.quick-links
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              Home
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              About
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              FAQ
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              Get Started
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              Videos
      .col-xs-12.col-sm-4.col-md-4
        %h5 Quick links
        %ul.list-unstyled.quick-links
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              Home
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              About
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              FAQ
          %li
            %a{:href => "javascript:void();"}
              %i.fa.fa-angle-double-right>
              Get Started
          %li
            %a{:href => "https://wwwe.sunlimetech.com", :title => "Design and developed by"}
              %i.fa.fa-angle-double-right>
              Imprint
    
    .row
      .col-xs-12.col-sm-12.col-md-12.mt-2.mt-sm-2.text-center.text-white
        %p
          %u
            %a{:href => "https://www.nationaltransaction.com/"} National Transaction Corporation
          is a Registered MSP/ISO of Elavon, Inc. Georgia [a wholly owned subsidiary of U.S. Bancorp, Minneapolis, MN]
        %p.h6
          \&copy All right Reversed.
          %a.text-green.ml-2{:href => "https://www.sunlimetech.com", :target => "_blank"} Sunlimetech

app/views/layouts/_maintenance.html.haml
.container
  .row
    =image_tag("logo.png")
  
  .row
    =image_tag("queue_1.jpg") 
  %h1 Sorry about that...
  %h5#suspended The website is currently offline until further notice
  %p 
    If you're an Admin you can 
    %a{:href => "/login"} Log in here
    to restore it
     

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{:role => 'navigation'}
  .navbar-header
    =link_to (root_path) do
      =image_tag("logo.png")
  .float-sm-right
    -if current_user
      =link_to ('/conversations') do
        =image_tag("mail.svg",class:"navicon1")
      =link_to (current_user) do
        =image_tag("person.svg",class:"navicon2")
      =link_to (new_room_path) do
        %button.btn.btn-success#create Create a room
      =link_to logout_path do
        %button.btn.btn-danger
          Logout
    -else
      =link_to signup_path do
        %button.btn.btn-primary Sign up
      =link_to login_path do
        %button.btn.btn-outline-primary Log in
      

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = yield(:title) 
      | Inline
    = csrf_meta_tags
    = csp_meta_tag
   
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src='https://npmcdn.com/@turf/turf/turf.min.js'></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    %script{src: "https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.2.0/mapbox-gl-geocoder.min.js"}
    %link{href: "https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.2.0/mapbox-gl-geocoder.css", rel: "stylesheet", type: "text/css"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'navbar'

  %body
    -if current_user && current_user.admin
      =render "layouts/dashboard"

    -if $should_be_offline==false
      =render "layouts/navbar"

      .container#flash_div
        - flash.each do |message_type, message|
          %div{class: "alert alert-#{message_type}"}= message
      = yield
    -else
      =render "layouts/maintenance"

    /= debug(params) if Rails.env.development?